= Advanced OpenShift Development ILT Homework Grading

This repository contains the scripts that students can use to validate that their homework assignment will pass.

The automatic grading process requires a public student repository on a Git compatible source code repository. This can be on Github or a custom public Gogs installation.

== Student Repository Structure

A skeleton student repository is provided at https://github.com/wkulhanek/advdev_homework_template.

See the homework assignment lab on instructions what to implement. Also see the README files in the skeleton repo (and it's three service subdirectories) on how to build and deploy the applications.

== Grading process

As part of the grading the student's scripts are being executed by a pipeline. If the entire pipeline finishes successfully the homework assignment is graded as *passed*. If the pipeline fails the homework assignmend is graded as *failed*.

Students can verify that the homework assignment will pass by running the pipeline themselves before submitting the assignment.

== How to set up the Jenkins to run the test

. Create a Jenkins Project in your cluster (e.g. `grading-jenkins`).
. Allow the `jenkins` service account to create projects
+
[source,bash]
----
oc adm policy add-cluster-role-to-user self-provisioner system:serviceaccount:grading-jenkins:jenkins
----
+
. Create a Persistent Jenkins with 2Gi memory in that project.
. Create a new Item in Jenkins of type `Pipeline`.
. Use the following settings in the Item:
.. This build is parametrized
.. Create five parameters:
* *GUID* (type String):    GUID to prefix all projects
* *USER* (type String):    OpenTLC User ID (e.g. wkulhane-redhat.com) to grant admin access for created projects for
* *REPO* (type String):    full URL to the public Homework Repo (either Gogs or Github)
* *CLUSTER* (type String): Cluster base URL. E.g. na39.openshift.opentlc.com
* *SETUP* (type Boolean):  Default: true
** If *true* will create all necessary projects.
** If *false* assumes that projects are already there and only pipelines need to be executed.
* *DELETE* (type Boolean): Default: true
** If *true* will delete all created projects after a successful run.
. Use https://github.com/wkulhanek/advdev_homework_grading as the Git Repo and 'Jenkinsfile' as the Jenkinsfile.

Now you are ready to try the pipeline. Run the pipeline and provide the appropriate parameters for your environment.

The pipeline will:

* Check out your source code repository
* Call your shell scripts to
** Create projects
** Setup Nexus
** Setup SonarQube
** Setup Jenkins
** Setup the Development Project
** Setup the Production Project
* Execute the pipelines for your three microservices for the initial (green) deployment.
* Check that the services return the correct application name
* Execute the pipelines again to execute the blue deployment
* Again check that the services return the correct application name
* Delete the projects

If the pipeline completes successfully you have passed the homework assignment.
